import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { NavBar } from "./components/NavBar";
import { ThemeProvider } from "./components/ThemeProvider";
import Sidebar from "@/components/sidebar";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>

  
    <html lang="en" suppressHydrationWarning>

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange>

     
        <div className="min-h-screen w-full bg-background text-foreground flex flex-col">

<NavBar/>
        <div className="flex flex-1 px-14 py-6 gap-6">
<Sidebar/>
        {children}
        </div>
        </div>
        </ThemeProvider>
      </body>
    </html>
    </ClerkProvider>
  );
}
 